---
- name: vps_setup
  hosts: localhost
  become: true

  vars:
    pg_data_dir: "/opt/postgres/data"
    caddy_site_dir: "/var/www/"

    #these all come from the .env, sample in this repo
    #lookup might work weird when I'm running on a remote host.
    #i'm only ever using localhost, so this works for me.
    ansible_user: '{{ lookup("env","ANSIBLE_USER") }}'
    pg_user: '{{ lookup("env", "PG_USER") }}'
    pg_password: '{{ lookup("env", "PG_PASSWORD") }}'
    pg_db: '{{ lookup("env", "PG_DB") }}'
    server_domain: '{{ lookup("env", "SERVER_DOMAIN") }}'

  roles:
    - apt
    #- docker_psql
    - native_psql
    - caddy
    - ufw








