- name: Update apt cache
  apt:
    update_cache: yes

- name: Install required apt packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - software-properties-common
      - unzip
      - ufw
      - python3
      - vim
    state: present