# ----------------------
# Install PostgreSQL from APT
# ----------------------

- name: Install PostgreSQL
  apt:
    # we need psycopg2 in order to use the ansible postgresql_db commands below
    # we might not need postgresql-contrib, but including just in case
    name: [postgresql, postgresql-contrib, python3-psycopg2]
    state: present
    update_cache: yes

- name: Ensure PostgreSQL service is enabled and running
  systemd:
    name: postgresql
    enabled: yes
    state: started

# ----------------------
# Configure PostgreSQL
# ----------------------

- name: Ensure PostgreSQL user exists
  become_user: postgres
  postgresql_user:
    name: "{{ pg_user }}"
    password: "{{ pg_password }}"
    role_attr_flags: CREATEDB,LOGIN

- name: Ensure initial database exists (optional, if you want pg_db created)
  become_user: postgres
  postgresql_db:
    name: "{{ pg_db }}"
    owner: "{{ pg_user }}"
    encoding: 'UTF8'
    lc_collate: 'en_US.UTF-8'
    lc_ctype: 'en_US.UTF-8'
    state: present

# ----------------------
# Create additional databases from db_list.txt
# ----------------------

- name: Read database list
  set_fact:
    db_list: "{{ lookup('file', role_path + '/files/db_list.txt').splitlines() }}"

- name: Create databases from list
  become_user: postgres
  postgresql_db:
    name: "{{ item }}"
    owner: "{{ pg_user }}"
    encoding: 'UTF8'
    lc_collate: 'en_US.UTF-8'
    lc_ctype: 'en_US.UTF-8'
    state: present
  loop: "{{ db_list }}"
