# ----------------------
# Install Docker, give myself permissions to start containers
# ----------------------

- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Add Docker apt repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
    state: present
    filename: docker

- name: Install Docker
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: latest
    update_cache: yes

- name: Add user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

- name: Enable and start Docker
  systemd:
    name: docker
    enabled: yes
    state: started


# ----------------------
# PostgreSQL with Docker Compose
# ----------------------

- name: Create PostgreSQL data directory
  file:
    path: "{{ pg_data_dir }}"
    state: directory
    owner: 999
    group: 999
    mode: '0755'


- name: Copy docker-compose.yml
  copy:
    dest: /opt/postgres/docker-compose.yml
    content: |
      version: '3.8'

      services:
        db:
          image: postgres:15
          container_name: db
          restart: unless-stopped
          environment:
            POSTGRES_USER: {{ pg_user }}
            POSTGRES_PASSWORD: {{ pg_password }}
            POSTGRES_DB: {{ pg_db }}
          volumes:
            - ./data:/var/lib/postgresql/data
          ports:
            - "5432:5432"

- name: Start PostgreSQL via docker compose CLI
  shell: docker compose up -d
  args:
    chdir: /opt/postgres

- name: Wait for PostgreSQL to be ready
  wait_for:
    port: 5432
    host: 127.0.0.1
    delay: 5
    timeout: 60

# ----------------------
# Create databases in pg
# ----------------------
# note: for now, I'm creating a single user, and having that
# user create and own everything in the databases list. 
- name: Create PostgreSQL databases from file via docker exec
  shell: |
    docker compose exec -T db psql -U {{ pg_user }} -c "CREATE DATABASE {{ item }};"
  with_lines: "cat {{ role_path }}/files/db_list.txt"
  environment:
    PGPASSWORD: "{{ pg_password }}"
  args:
    chdir: /opt/postgres